name: HCBank
main: core.start.Main
version: 1.1
author: AddonGaming
commands:
   setbankchest:
      description: Face a chest and use the command to set the bank chest.
   checkbankchest:
      description: .