name: PlayerBank
main: me.m0r3tank1ng.PlayerBank
version: 1.0

commands:
   createbank:
      description: You can use this command to create the bank for your server.
      usage: /<command>
      permission: playerbank.create
      permission-message: You don't have <permission> to execute this command.